version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-dinostocks-db
    environment:
      POSTGRES_DB: dinostocks_db
      POSTGRES_USER: megan
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dino-app-backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      PYTHONPATH: /backend/dependencies

  frontend:
    build:
      context: ./front_end/dino_stocks
      dockerfile: Dockerfile
    container_name: dino-app-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
