# Generated by Django 5.0 on 2023-12-28 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historicals', to='portfolio_app.portfolio')),
            ],
        ),
    ]
