# Generated by Django 5.0 on 2023-12-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historicals_app', '0003_alter_historicals_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicals',
            old_name='value',
            new_name='portfolio_value',
        ),
    ]
