# Generated by Django 5.0 on 2023-12-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicals_app', '0004_rename_value_historicals_portfolio_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicals',
            name='portfolio_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
