apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinostocks-backend-deployment
  namespace: otterpenguin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dinostocks-backend
  template:
    metadata:
      labels:
        app: dinostocks-backend
    spec:
      initContainers:
      - name: init-migrate
        image: tsmith4014/dino-app-backend:latest
        command: ["python", "manage.py", "migrate"]
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        envFrom:
        - configMapRef:
            name: dinostocks-configmap
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dinostocks-secrets
              key: DB_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: dinostocks-secrets
              key: SECRET_KEY
      - name: init-loaddata
        image: tsmith4014/dino-app-backend:latest
        command: ["python", "manage.py", "loaddata", "stock_data.json"]
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        envFrom:
        - configMapRef:
            name: dinostocks-configmap
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dinostocks-secrets
              key: DB_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: dinostocks-secrets
              key: SECRET_KEY
      containers:
      - name: dinostocks-backend
        image: tsmith4014/dino-app-backend:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: dinostocks-secrets
              key: SECRET_KEY