apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinostocks-database
  namespace: otterpenguin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dinostocks-database
  template:
    metadata:
      labels:
        app: dinostocks-database
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: dinostocks-configmap
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dinostocks-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: dinostocks-configmap
                  key: DB_NAME
            - name: POSTGRES_INITDB_ARGS
              valueFrom:
                configMapKeyRef:
                  name: dinostocks-configmap
                  key: POSTGRES_INITDB_ARGS