apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinostocks-backend-deployment
  namespace: otterpenguin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dinostocks-backend
  template:
    metadata:
      labels:
        app: dinostocks-backend
    spec:
      containers:
      - name: dinostocks-backend
        image: tsmith4014/dino-app-backend:latest
        ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: dinostocks-configmap
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dinostocks-secrets
                key: DB_PASSWORD
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: dinostocks-configmap
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: dinostocks-configmap
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: dinostocks-configmap
                key: DB_NAME
          - name: RAPID_API_KEY  # Added this section
            valueFrom:
              secretKeyRef:
                name: dinostocks-secrets
                key: RAPID_API_KEY