apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinostocks-frontend
  namespace: otterpenguin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dinostocks-frontend
  template:
    metadata:
      labels:
        app: dinostocks-frontend
    spec:
      containers:
      - name: dinostocks-frontend
        image: tsmith4014/dino-app-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "100m"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config