apiVersion: v1
kind: Service
metadata:
  name: dinostocks-frontend
  namespace: otterpenguin
spec:
  type: NodePort
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30080
  selector:
    app: dinostocks-frontend