apiVersion: v1
kind: ConfigMap
metadata:
  name: dinostocks-configmap
  namespace: otterpenguin
data:
  #Variables for database and backend
  DB_USER: admin
  DB_HOST: dinostocks-database
  DB_NAME: dinostocks_db
  DB_PORT: "5432"
  #Variable specific to database init
  POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C --data-checksums"

  #Variables for frontend
  REACT_APP_BACKEND_HOST: dinostocks-backend # from front_end/dino_stocks/srs/utilities.jsx
  REACT_APP_BACKEND_PORT: "8000" # from front_end/dino_stocks/srs/utilities.jsx