apiVersion: v1
kind: Service
metadata:
  name: dinostocks-frontend
  namespace: otterpenguin
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dinostocks-frontend
  type: LoadBalancer