apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinostocks-redis-deployment
  namespace: otterpenguin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dinostocks-redis
  template:
    metadata:
      labels:
        app: dinostocks-redis
    spec:
      containers:
      - name: dinostocks-redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"