const descriptions = {
    "MICRO": "Investing in the Microraptor is a smart choice for your dinosaur portfolio! This dino is like the park's superstar because of its cool feathers and super agility. People love to watch it zip around and do awesome tricks. Just like how a popular toy or game can make a company lots of money, having the Microraptor in our park makes everyone excited to come and visit. It's kind of like when everyone wants the newest video game. So, by getting shares of the Microraptor, you're investing in the dino everyone loves to see, and that can mean more visitors and more money for our theme park!",
    "TREX": "Investing in the T-Rex at the theme park is a smart move. The T-Rex is like the rockstar of the park – it's big, powerful, and everyone wants to see it. When you invest in the T-Rex, it's like being a part-owner of the main attraction. The T-Rex is a crowd-puller, bringing in lots of visitors who are willing to pay to see this legendary dinosaur. So, investing in the T-Rex doesn't just make sense; it's like having a share in the most exciting and popular part of the entire theme park!",
    "VELO": "Investing in the Velociraptor is a clever choice for your dinosaur portfolio! Velociraptors are like the theme park's energetic entertainers. They're quick, smart, and always put on a thrilling show. Just like how people love watching fast and clever characters in movies, visitors adore seeing the Velociraptor in action. By having shares of the Velociraptor, you're investing in a dino that brings excitement and energy to the park, making it a favorite among visitors and potentially boosting our park's popularity and profits!",
    "STEGO": "Investing in the Stegosaurus is a super cool choice for your dinosaur portfolio! This dino is the friendly giant of the park, with its awesome spiked tail and big plates on its back. The Stegosaurus is like the staple that everyone wants to see because it's both fascinating and gentle. Families love to visit the Stegosaurus because it's like meeting a real-life dinosaur celebrity. So, if you want to be part of the excitement and have a dino that steals the show, the Stegosaurus is the perfect choice for your investment.",
    "TRI": "Investing in the Triceratops is a solid choice for your dinosaur portfolio! Triceratops are like the park's charming herbivores. With their three distinctive horns and protective frill, they're a crowd-pleaser for dinosaur enthusiasts. Families and kids love getting up close to these friendly giants. By having shares of the Triceratops, you're investing in a dino that adds a touch of charm to the park, attracting visitors who appreciate the fascinating world of herbivorous dinosaurs!",
    "BRACH": "Investing in the Brachiosaurus is a smart move for your dinosaur portfolio! The Brachiosaurus is like the park's towering icon, reaching for the skies with its long neck. Visitors are captivated by its sheer size and majestic presence. Like an iconic landmark in a theme park, the Brachiosaurus draws attention and becomes a memorable symbol. By having shares of the Brachiosaurus, you're investing in a dino that stands out and makes the park an unforgettable destination!",
    "ANKY": "Investing in the Ankylosaurus is a strategic choice for your dinosaur portfolio! The Ankylosaurus is like the park's armored warrior, equipped with a sturdy tail club and thick, protective armor. Visitors are fascinated by its unique features, and it adds an element of strength and resilience to the park. By having shares of the Ankylosaurus, you're investing in a dino that symbolizes toughness and captures the interest of visitors seeking a glimpse of prehistoric strength!",
    "PTERO": "Investing in the Pterodactyl is an adventurous choice for your dinosaur portfolio! The Pterodactyl is like the park's flying sensation, soaring gracefully through the air. Visitors marvel at its wingspan and the freedom of flight. Like an exciting aerial show, the Pterodactyl adds an element of wonder to the park. By having shares of the Pterodactyl, you're investing in a dino that brings the magic of flight to the park, captivating audiences and creating memorable experiences!",
    "SPINO": "Investing in the Spinosaurus is a thrilling choice for your dinosaur portfolio! The Spinosaurus is like the park's aquatic adventurer, known for its sail-like fin and fearsome presence. Visitors are drawn to its aquatic habitat, creating a unique and exciting exhibit. By having shares of the Spinosaurus, you're investing in a dino that adds an element of mystery and adventure to the park, attracting thrill-seekers and those fascinated by prehistoric aquatic life!",
    "ALLO": "Investing in the Allosaurus is a bold choice for your dinosaur portfolio! The Allosaurus is like the park's carnivorous king, known for its predatory prowess and sharp teeth. Visitors are intrigued by its hunting behaviors and the thrill of seeing a top predator in action. By having shares of the Allosaurus, you're investing in a dino that brings a touch of excitement and danger to the park, appealing to those who seek the thrill of encountering a fearsome predator!",
    "APTO": "Investing in the Apatosaurus is a heartwarming choice for your dinosaur portfolio! The Apatosaurus is like the park's gentle giant, known for its long neck and herbivorous nature. Families appreciate the friendly demeanor of this massive dinosaur, making it a popular attraction for all ages. By having shares of the Apatosaurus, you're investing in a dino that creates a sense of awe and wonder, becoming a beloved figure that families love to visit and learn about!",
    "DILO": "Investing in the Dilophosaurus is an intriguing choice for your dinosaur portfolio! The Dilophosaurus is like the park's colorful and charismatic dino, recognized for its crests and distinctive appearance. Visitors are drawn to its unique features and lively demeanor. By having shares of the Dilophosaurus, you're investing in a dino that stands out, capturing the attention of those who appreciate the diversity of prehistoric life and enjoy encountering dinos with distinctive characteristics!",
    "PARA": "Investing in the Parasaurolophus is a melodious choice for your dinosaur portfolio! The Parasaurolophus is like the park's musical marvel, recognized for its elaborate crest that resembles a musical instrument. Visitors are enchanted by its unique appearance and the possibility of dinosaur sounds. By having shares of the Parasaurolophus, you're investing in a dino that adds a touch of whimsy and creativity to the park, appealing to those who appreciate the artistry of prehistoric life!",
    "ARCH": "Investing in the Archaeopteryx is a fascinating choice for your dinosaur portfolio! The Archaeopteryx is like the park's avian marvel, considered one of the earliest birds. Visitors are intrigued by its feathered appearance and the link between dinosaurs and modern birds. By having shares of the Archaeopteryx, you're investing in a dino that sparks curiosity and offers a glimpse into the evolutionary journey of prehistoric creatures, attracting those interested in the connection between dinosaurs and birds!",
    "IGUA": "Investing in the Iguanodon is a classic choice for your dinosaur portfolio! The Iguanodon is like the park's iconic herbivore, recognized for its thumb spike and significant role in early dinosaur discoveries. Visitors appreciate the historical significance of encountering this dinosaur, making it a timeless attraction. By having shares of the Iguanodon, you're investing in a dino that represents a piece of paleontological history, appealing to those who value the exploration and understanding of ancient life!",
    "PACHY": "Investing in the Pachycephalosaurus is an exhilarating choice for your dinosaur portfolio! The Pachycephalosaurus is like the park's head-banging sensation, known for its thick skull and unique behavior. Visitors are amused by its distinctive appearance and the entertaining displays of head-butting. By having shares of the Pachycephalosaurus, you're investing in a dino that brings laughter and excitement to the park, appealing to those who enjoy the playful and dynamic side of prehistoric life!",
    "CORY": "Investing in the Corythosaurus is a harmonious choice for your dinosaur portfolio! The Corythosaurus is like the park's musical maestro, known for its distinctive crest that resembles a helmet. Visitors are enchanted by its elegant appearance and the possibility of musical sounds. By having shares of the Corythosaurus, you're investing in a dino that adds a touch of artistry and charm to the park, appealing to those who appreciate the beauty of prehistoric life!",
    "PLESI": "Investing in the Plesiosaurus is a captivating choice for your dinosaur portfolio! The Plesiosaurus is like the park's aquatic marvel, known for its long neck and flippers. Visitors are fascinated by its unique adaptations to aquatic life, creating an exciting underwater exhibit. By having shares of the Plesiosaurus, you're investing in a dino that brings the wonders of the prehistoric sea to the park, attracting those who are curious about the diverse life that once inhabited our planet's oceans!",
    "CARNO": "Investing in the Carnotaurus is an adrenaline-pumping choice for your dinosaur portfolio! The Carnotaurus is like the park's speedster, recognized for its muscular build and distinctive horns. Visitors are thrilled by its powerful appearance and the idea of encountering a dinosaur built for speed. By having shares of the Carnotaurus, you're investing in a dino that adds an element of excitement and adventure to the park, attracting those who seek the thrill of witnessing a fast and formidable predator!",
    "DEINO": "Investing in the Deinonychus is a strategic choice for your dinosaur portfolio! The Deinonychus is like the park's cunning hunter, known for its intelligence and pack behavior. Visitors are captivated by its hunting strategies and the opportunity to witness the intelligence of a dino. By having shares of the Deinonychus, you're investing in a dino that adds an element of strategy and intrigue to the park, appealing to those who appreciate the complex behaviors of prehistoric predators!"
}

export default descriptions